# Generated by Django 2.0 on 2020-02-13 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0030_auto_20200213_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarageDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gimage', models.ImageField(default='abc.jpg', upload_to='image/')),
                ('Gname', models.CharField(max_length=25)),
                ('Gaddress', models.CharField(max_length=254)),
                ('City', models.CharField(max_length=10)),
                ('Mobile_No', models.CharField(max_length=10)),
                ('Ser1', models.CharField(max_length=25)),
                ('Ser2', models.CharField(max_length=25)),
                ('Ser3', models.CharField(max_length=25)),
                ('Ser4', models.CharField(max_length=25)),
                ('Ser5', models.CharField(max_length=25)),
                ('Ser6', models.CharField(max_length=25)),
                ('SP_ID', models.ForeignKey(default='abc@gmail.com', on_delete=django.db.models.deletion.CASCADE, to='authapp.Master_Table')),
            ],
        ),
    ]
