# Generated by Django 2.0 on 2020-02-15 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garagedetails',
            name='Ser1_Price',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='garagedetails',
            name='Ser2_Price',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='garagedetails',
            name='Ser3_Price',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='garagedetails',
            name='Ser4_Price',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='garagedetails',
            name='Ser5_Price',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='garagedetails',
            name='Ser6_Price',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='garagedetails',
            name='SP_ID',
            field=models.ForeignKey(default='abc@gmail.com', on_delete=django.db.models.deletion.CASCADE, to='authapp.Master_Table'),
        ),
    ]
