# Generated by Django 2.0 on 2020-02-23 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providerapp', '0002_auto_20200215_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='garagedetails',
            name='Provider_Name',
            field=models.CharField(default='abc', max_length=50),
        ),
        migrations.AlterField(
            model_name='garagedetails',
            name='SP_ID',
            field=models.ForeignKey(default='abc@gmail.com', on_delete=django.db.models.deletion.CASCADE, to='authapp.Master_Table'),
        ),
    ]
