# Generated by Django 2.0 on 2020-03-07 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providerapp', '0003_auto_20200223_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garagedetails',
            name='Ser6',
        ),
        migrations.RemoveField(
            model_name='garagedetails',
            name='Ser6_Price',
        ),
        migrations.AlterField(
            model_name='garagedetails',
            name='SP_ID',
            field=models.ForeignKey(default='abc@gmail.com', on_delete=django.db.models.deletion.CASCADE, to='authapp.Master_Table'),
        ),
    ]
