# Generated by Django 2.0 on 2020-03-07 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providerapp', '0004_auto_20200307_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garagedetails',
            name='SP_ID',
            field=models.ForeignKey(default='abc@gmail.com', on_delete=django.db.models.deletion.CASCADE, to='authapp.Master_Table'),
        ),
        migrations.AlterField(
            model_name='garagedetails',
            name='Ser1_Price',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='garagedetails',
            name='Ser2_Price',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='garagedetails',
            name='Ser3_Price',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='garagedetails',
            name='Ser4_Price',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='garagedetails',
            name='Ser5_Price',
            field=models.CharField(max_length=25),
        ),
    ]
