# Generated by Django 2.0 on 2020-03-10 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providerapp', '0005_auto_20200307_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garagedetails',
            name='SP_ID',
            field=models.ForeignKey(default='abc@gmail.com', on_delete=django.db.models.deletion.CASCADE, to='authapp.Master_Table'),
        ),
    ]
