# Generated by Django 2.0 on 2020-03-20 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providerapp', '0010_auto_20200319_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='garagedetails',
            name='Ser6',
            field=models.CharField(default='none', max_length=25),
        ),
        migrations.AddField(
            model_name='garagedetails',
            name='Ser6_Price',
            field=models.CharField(default='none', max_length=25),
        ),
        migrations.AddField(
            model_name='garagedetails',
            name='Ser7',
            field=models.CharField(default='none', max_length=25),
        ),
        migrations.AddField(
            model_name='garagedetails',
            name='Ser7_Price',
            field=models.CharField(default='none', max_length=25),
        ),
        migrations.AlterField(
            model_name='garagedetails',
            name='SP_ID',
            field=models.ForeignKey(default='abc@gmail.com', on_delete=django.db.models.deletion.CASCADE, to='authapp.Master_Table'),
        ),
    ]
