# Generated by Django 2.0 on 2020-01-12 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_manager',
            name='PassWord',
        ),
        migrations.RemoveField(
            model_name='user',
            name='PassWord',
        ),
    ]
