# Generated by Django 2.0 on 2020-01-27 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20200112_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='product_manager',
            name='PM_Id',
        ),
        migrations.RenameField(
            model_name='master_table',
            old_name='created_at',
            new_name='Created_At',
        ),
        migrations.RenameField(
            model_name='master_table',
            old_name='is_active',
            new_name='Is_Active',
        ),
        migrations.RenameField(
            model_name='master_table',
            old_name='is_verfied',
            new_name='Is_Verfied',
        ),
        migrations.RenameField(
            model_name='master_table',
            old_name='PassWord',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='master_table',
            old_name='updated_at',
            new_name='Updated_At',
        ),
        migrations.AlterField(
            model_name='user',
            name='User_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.Master_Table'),
        ),
        migrations.DeleteModel(
            name='Product_Manager',
        ),
        migrations.AddField(
            model_name='service_provider',
            name='SP_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.Master_Table'),
        ),
    ]
