# Generated by Django 2.0 on 2020-02-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_auto_20200207_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master_table',
            name='id',
        ),
        migrations.AlterField(
            model_name='master_table',
            name='Email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='service_provider',
            name='SP_Id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_Id',
            field=models.IntegerField(),
        ),
    ]
