# Generated by Django 2.0 on 2020-03-19 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0038_auto_20200310_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Part_Image', models.ImageField(default='abc.jpg', upload_to='image/')),
                ('Part', models.CharField(max_length=50)),
                ('Sub_Part', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=150)),
                ('Brand', models.CharField(max_length=40)),
                ('Price', models.CharField(max_length=60)),
                ('Fitment', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='service_provider',
            name='SP_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.Master_Table'),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.Master_Table'),
        ),
    ]
