# Generated by Django 2.0 on 2020-03-19 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0040_auto_20200319_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part_Camshaft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bike_Name', models.CharField(max_length=30)),
                ('Bike_Model', models.CharField(max_length=30)),
                ('Price', models.CharField(max_length=30)),
                ('Availibility', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='service_provider',
            name='SP_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.Master_Table'),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.Master_Table'),
        ),
    ]
