# Generated by Django 2.0 on 2020-01-13 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactUsForm',
        ),
    ]
