# Generated by Django 2.0 on 2020-01-27 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20200113_2251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUsForm',
        ),
    ]
