# Generated by Django 2.0 on 2020-02-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0003_delete_contactusform'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Subject', models.CharField(max_length=30)),
                ('Mesage', models.CharField(max_length=50)),
            ],
        ),
    ]
