# Generated by Django 2.0 on 2020-02-07 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_user_query'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_query',
            old_name='Mesage',
            new_name='Message',
        ),
    ]
