# Generated by Django 2.0 on 2020-02-09 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_master_vehicle_user_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_vehicle',
            name='Vnumber',
        ),
        migrations.AlterField(
            model_name='master_vehicle',
            name='User_ID',
            field=models.ForeignKey(default='abc@gmail.com', on_delete=django.db.models.deletion.CASCADE, to='authapp.Master_Table'),
        ),
    ]
