# Generated by Django 2.0 on 2020-02-15 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_auto_20200215_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_vehicle',
            name='User_ID',
            field=models.ForeignKey(default='abc@gmail.com', on_delete=django.db.models.deletion.CASCADE, to='authapp.Master_Table'),
        ),
    ]
