# Generated by Django 2.0 on 2020-03-10 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0037_auto_20200310_1011'),
        ('userapp', '0014_auto_20200307_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=30)),
                ('Need', models.CharField(max_length=30)),
                ('Vehicle_ID', models.CharField(max_length=30)),
                ('Provider_ID', models.ForeignKey(default='abc@gmail.com', on_delete=django.db.models.deletion.CASCADE, to='authapp.Master_Table')),
            ],
        ),
        migrations.AlterField(
            model_name='master_vehicle',
            name='User_ID',
            field=models.ForeignKey(default='abc@gmail.com', on_delete=django.db.models.deletion.CASCADE, to='authapp.Master_Table'),
        ),
    ]
