# Generated by Django 2.0 on 2020-03-20 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0020_auto_20200320_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_vehicle',
            name='User_ID',
            field=models.ForeignKey(default='abc@gmail.com', on_delete=django.db.models.deletion.CASCADE, to='authapp.Master_Table'),
        ),
    ]
