# Generated by Django 3.2 on 2021-05-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0021_auto_20200320_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_query',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
    ]
